[package]
name = "rusty-life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
dotenv = "0.15.0"
env_logger = "0.10.0"
ggez = "0.9.3"
log = "0.4.20"
rand = "0.8.5"
regex = "1.10.2"
